#!/usr/bin/env node
const fs = require('fs')
const file = './index.json'
const read = fs.readFileSync(file, 'utf8')
const formatted = JSON.stringify(JSON.parse(read), null, 2)
fs.writeFileSync(file, formatted + '\n')
